### ISSUE TITLE
Refactor animations code to share code as much as possible

### ISSUE THREAD

**Issue by artoale** [artoale/ng-cat#41]
Currently, most of the animations code has some degree of duplication. This not only is generally speaking bad practise, but it makes it hard to write new "base" animation

**Comment by flea89** [comment]
@artoale I'll be carrying on refactoring tests.
Quite a few of them will change, this refactor should simplify the testing as well: most of the general logic can now be tested in catAnimationLink and catBaseAnimation, while we can now test just the effective animation code per directive.

**Comment by flea89** [comment]
I've been refactoring and fixing few issues. @artoale can you please review this?

**Comment by artoale** [comment]
Merged.
