### ISSUE TITLE
More `utils` tests

### ISSUE THREAD

**Issue by artoale** [artoale/ng-cat#44]
Since we're refactoring the scrollspy out of ng-cat, there's no need to improve coverage here (to be done there). Need to properly test utils module though.

@flea89 IIRC you where saying there's some sort of unreported bug in the scroll-helper service. Can you confirm/elaborate?

**Comment by flea89** [comment]
That's correct, currently if the page doesn't have enough content to be scrolled the feature detection fails and the wrong scroll-container is detected.

However this is affecting just the scrollspy module and hopefully we will move that code to a new repo
#45, we will be probably tackling that there.
What you think @artoale ?

**Comment by flea89** [comment]
After moving the spy to his own repo we have a great 99.17% coverage https://codecov.io/github/artoale/angular-cat/src/js?ref=4bee55ee805d1447e352b4d41f24ec041b8a6d79

I'll close this one
