### ISSUE TITLE
Move scroll-spy to his own repo.

### ISSUE THREAD

**Issue by flea89** [artoale/ng-cat#45]
The scroll spy is currently a nice-to-have module for ng-cat but shouldn't be in the core module.
The reasons why I am saying this are:
- Scroll-spy module might be useful in project where all the animations infrastructure is not required.
- There are several use-cases where animations the scroll-spy won't be used together with animations ( ie. interaction based kind of animations)
- All the usual pros of splitting code in smaller/reusable modules.

I've created the new repo [here](https://github.com/flea89/ng-spy) and planning to do some work on it soon.

**Comment by flea89** [comment]
@artoale can you please double check this, we can then deploy a new version

**Comment by artoale** [comment]
Merged into `develop`
